service: sol-arb-api

custom:
  secrets: ${file(config.prod.yml)}

frameworkVersion: "2"

provider:
  name: aws
  runtime: go1.x
  stage: ${self:custom.secrets.ENV}

plugins:
  - serverless-go-build # dont need makefile

package:
  individually: true

functions:
  check_token_trackers:
    handler: entrypoints/check_token_trackers/main.go
    environment:
      DB_NAME: ${self:custom.secrets.DB_NAME}
      DB_HOST: ${self:custom.secrets.DB_HOST}
      DB_USER: ${self:custom.secrets.DB_USER}
      DB_PWD: ${self:custom.secrets.DB_PWD}
      ALERTER_DISCORD_ID: ${self:custom.secrets.ALERTER_DISCORD_ID}
      DISCORD_BOT_TOKEN: ${self:custom.secrets.DISCORD_BOT_TOKEN}
    events:
      - http:
          path: check_token_trackers
          method: post
          cors:
            origin: ${self:custom.secrets.ALLOWED_ORIGIN}
            allowCredentials: "true"

  token_trackers:
    handler: entrypoints/token_trackers/main.go
    environment:
      DB_NAME: ${self:custom.secrets.DB_NAME}
      DB_HOST: ${self:custom.secrets.DB_HOST}
      DB_USER: ${self:custom.secrets.DB_USER}
      DB_PWD: ${self:custom.secrets.DB_PWD}
    events:
      - http:
          path: token_trackers/by-discord-id/{discordId}
          method: any
          cors:
            origin: ${self:custom.secrets.ALLOWED_ORIGIN}
            allowCredentials: "true"
